name: yakssok-pr-check

on:
  pull_request:
    branches: [ "main", "dev" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”½ Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ”§ Make gradlew executable
        working-directory: ./yakssok
        run: chmod +x gradlew
        
      - name: ğŸ“ Create application-test.yml from secret
        working-directory: ./yakssok
        run: |
          mkdir -p src/test/resources
          echo "${{ secrets.TEST_YML }}" > src/test/resources/application-test.yml

      - name: ğŸ›  Build (without retesting)
        working-directory: ./yakssok
        run: ./gradlew build -x test
